### ISSUE TITLE
reqwest_retry 0.3 breaks build_with_total_retry_duration

### ISSUE THREAD

**Issue by Jimmy-Z** [TrueLayer/reqwest-middleware#107] opened 2023-09-18 09:25 UTC
Previously `build_with_total_retry_duration` returns `ExponentialBackoff`:
https://docs.rs/reqwest-retry/0.2.3/reqwest_retry/policies/struct.ExponentialBackoffBuilder.html#method.build_with_total_retry_duration

In 0.3 it returns `ExponentialBackoffTimed` instead, which doesn't implement `RetryPolicy`
and not acceptable to `RetryTransientMiddleware::new_with_policy`:
https://docs.rs/reqwest-retry/latest/reqwest_retry/policies/struct.ExponentialBackoffBuilder.html#method.build_with_total_retry_duration
https://docs.rs/reqwest-retry/latest/reqwest_retry/struct.RetryTransientMiddleware.html#method.new_with_policy

Or did I overlook some other way?

**Comment by tl-rodrigo-gryzinski** [comment] 2023-09-18 09:38
Duplicate of #106, this was a breaking change in `retry-policies`, reasoning [here](https://github.com/TrueLayer/retry-policies/pull/10).

**Closed by tl-rodrigo-gryzinski** 2023-09-18 09:38 UTC
Labels: bug
